
### @ConfigurationProperties 테스트 값
test-property:
  value1: true
  value2: 1234


aws:
  s3:
    access-key: access-key value
    secret-key: secret-key value
    bucket: bucket value
  region:
    region-static: region-static value

s3:
  access-key: access-key value
  secret-key: secret-key value
  bucket:
    stage:
      - stage-bucket value 1
      - stage-bucket value 2
    production: production-bucket value

#############################


### Open API Swagger 설정 값
springdoc:
  swagger-ui:
    path: /custom/swagger-ui      # Swagger 기본 경로 설정
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, alpha-reverse: 알파벳 역순, original: 태그를 정의한 순서
    operations-sorter: method     # alpha: 알파벳 순 메서드 정렬, method: HTTP Method 순 정렬
                                  # alpha-reverse, method-reverse
  api-docs:
    path: /custom/api-docs        # docs 기본 경로 설정

########################



### Logging 관련 설정 값
logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    com.example: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/myapp/myapp.log
    total-size-cap: 10MB
    clean-history-on-start: true
  console:
    charset: UTF-8
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-history: 7

